
-- create
CREATE TABLE CLASSMATES (
  Id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adress TEXT NOT NULL
);

-- insert
INSERT INTO CLASSMATES VALUES (1, 'Dave', 20, 'Moscow');
INSERT INTO CLASSMATES VALUES (2, 'Max', 25, 'Moscow');
INSERT INTO CLASSMATES VALUES (3, 'Kate', 30, 'Moscow');
INSERT INTO CLASSMATES VALUES (4, 'Nik', 31, 'Moscow');
INSERT INTO CLASSMATES VALUES (5, 'Tom', 17, 'Moscow');
INSERT INTO CLASSMATES VALUES (6, 'Jarry', 18, 'Moscow');
INSERT INTO CLASSMATES VALUES (7, 'Kim', 21, 'Moscow');
INSERT INTO CLASSMATES VALUES (8, 'Dima', 20, 'Tomsk');
INSERT INTO CLASSMATES VALUES (9, 'Nina', 25, 'Spb');
INSERT INTO CLASSMATES VALUES (10, 'Boris', 18, 'Spb');
INSERT INTO CLASSMATES VALUES (11, 'Max', 30, 'Moscow');
INSERT INTO CLASSMATES VALUES (12, 'Tina', 25, 'Spb');
INSERT INTO CLASSMATES VALUES (13, 'Nika', 22, 'Moscow');
INSERT INTO CLASSMATES VALUES (14, 'Dann', 27, 'Moscow');
INSERT INTO CLASSMATES VALUES (15, 'Vova', 25, 'Moscow');
INSERT INTO CLASSMATES VALUES (16, 'Sergey', 32, 'Moscow');
INSERT INTO CLASSMATES VALUES (17, 'Alex', 35, 'Moscow');
INSERT INTO CLASSMATES VALUES (18, 'Roma', 20, 'Moscow');

-- fetch 
SELECT name FROM CLASSMATES WHERE adress = 'Moscow' AND age > 17 AND age < 30;
