GET https://nalog.ru

###

GET https://reqres.in/api/user/2
###
GET https://reqres.in/api/user/2
###
POST https://reqres.in/api/users?page=2

Content-Type: application/json
{
    "name": "morpheus",
    "job": "leader"
}
###